name: Auto commit

on:
  push:
    branches:
      - main      
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Explicitly set permissions
    steps:
      - name: DEBUG 
        run: echo "::debug::Ref = ${{github.ref}}"
        
      - name: Checkout repository
        uses: actions/checkout@v3      
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED
          
      - name: Commit changes
        run: |
          git config --local user.email "testing@testing.com"
          git config --local user.name "testing"
          git add -A
          
          # Only commit if there are changes
          if [ -n "$(git status --porcelain)" ]; then
            arr[0]="chore(bot): 😂 auto commit"
            arr[1]="chore(bot): 😱 auto commit"
            arr[2]="chore(bot): 👿 auto commit"
            arr[3]="chore(bot): 💩 auto commit"
            arr[4]="chore(bot): 🙏 auto commit"
            arr[5]="chore(bot): 🙈 auto commit"
            arr[6]="chore(bot): 🐐 auto commit"
            arr[7]="chore(bot): 🤖 auto commit"
            arr[8]="chore(bot): 🟩 auto commit"
            arr[9]="chore(bot): 👻 auto commit"
            
            rand=$[$RANDOM % ${#arr[@]}]
            git commit -m "${arr[$rand]}"
          fi
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.8.0  # Updated to latest version
        with:
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main   # Explicitly set branch
          force: true   # Force push to handle conflicts
